"use client";
import { useState } from "react";
import { Icon } from "@/components/ui/icon";

type Article={id:string;title:string;category:string;content:string;unit:string|null;status:string;visibility:string;updated_at:string};
export function KnowledgeBase({initial,migrationMissing}:{initial:Article[];migrationMissing:boolean}){
  const [items,setItems]=useState(initial),[open,setOpen]=useState(false),[notice,setNotice]=useState(""),[form,setForm]=useState({title:"",category:"Cursos e modalidades",content:"",unit:"",visibility:"customer",status:"published",valid_until:""});
  async function save(){const response=await fetch("/api/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)return setNotice(body.error);setItems(c=>[body,...c]);setOpen(false);setNotice("Conteúdo publicado para a IA.");}
  async function remove(item:Article){if(!window.confirm(`Excluir "${item.title}" da base de conhecimento? A IA deixa de usar essa informação.`))return;const response=await fetch(`/api/knowledge/${item.id}`,{method:"DELETE"});const body=await response.json();if(!response.ok)return setNotice(body.error);setItems(c=>c.filter(i=>i.id!==item.id));setNotice("Conteúdo excluído.");}
  async function toggleStatus(item:Article){const next=item.status==="published"?"draft":"published";const response=await fetch(`/api/knowledge/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:next})});const body=await response.json();if(!response.ok)return setNotice(body.error);setItems(c=>c.map(i=>i.id===item.id?body:i));setNotice(next==="published"?"Conteúdo publicado para a IA.":"Conteúdo despublicado (a IA não usa mais).");}
  if(migrationMissing)return <div className="config-required"><Icon name="book" size={28}/><h2>Base pronta para ativação</h2><p>Execute <code>002_agenda_knowledge.sql</code> no Supabase.</p></div>;
  return <div className="knowledge-shell"><section className="knowledge-toolbar"><div><strong>{items.filter(i=>i.status==="published").length} conteúdos publicados</strong><span>A IA utilizará somente informações publicadas e dentro da validade.</span></div><button className="button button-primary" onClick={()=>setOpen(!open)}><Icon name="plus" size={15}/> Novo conteúdo</button></section>
    {open&&<form className="knowledge-form" onSubmit={e=>{e.preventDefault();save();}}><div className="field-grid"><div className="field"><label>Título</label><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="field"><label>Categoria</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Cursos e modalidades</option><option>Unidades</option><option>Valores e condições</option><option>Horários e disponibilidade</option><option>Metodologia</option><option>Objeções comerciais</option><option>Políticas</option></select></div></div><div className="field"><label>Informação aprovada</label><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></div><div className="field-grid"><div className="field"><label>Unidade</label><select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="">Todas</option><option>Chapecó</option><option>Passo Fundo</option><option>Online</option></select></div><div className="field"><label>Válido até</label><input type="date" value={form.valid_until} onChange={e=>setForm({...form,valid_until:e.target.value})}/></div></div><button className="button button-primary">Publicar conteúdo</button></form>}
    {notice&&<div className="studio-notice ok">{notice}</div>}<section className="knowledge-grid">{items.map(i=><article key={i.id}><div><span>{i.category}</span><b className={i.status}>{i.status==="published"?"Publicado":"Rascunho"}</b></div><h3>{i.title}</h3><p>{i.content}</p><small>{i.unit||"Todas as unidades"} · Atualizado em {new Date(i.updated_at).toLocaleDateString("pt-BR")}</small><div className="knowledge-card-actions"><button type="button" onClick={()=>toggleStatus(i)}>{i.status==="published"?"Despublicar":"Publicar"}</button><button type="button" className="knowledge-delete" onClick={()=>remove(i)}><Icon name="x" size={12}/> Excluir</button></div></article>)}</section></div>;
}
